"""initial migration

Revision ID: 5eb1380d908a
Revises: 
Create Date: 2025-07-09 12:52:28.775165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5eb1380d908a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qc_parameters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('material', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('min_value', sa.Float(), nullable=True),
    sa.Column('max_value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qc_parameters_id'), 'qc_parameters', ['id'], unique=False)
    op.create_table('qc_tests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=True),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('performed_by', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.Column('attachment_filename', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qc_tests_id'), 'qc_tests', ['id'], unique=False)
    op.create_table('qc_test_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.String(), nullable=True),
    sa.Column('parameter_id', sa.Integer(), nullable=True),
    sa.Column('observed_value', sa.Float(), nullable=True),
    sa.Column('is_within_spec', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['parameter_id'], ['qc_parameters.id'], ),
    sa.ForeignKeyConstraint(['test_id'], ['qc_tests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qc_test_results_id'), 'qc_test_results', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_qc_test_results_id'), table_name='qc_test_results')
    op.drop_table('qc_test_results')
    op.drop_index(op.f('ix_qc_tests_id'), table_name='qc_tests')
    op.drop_table('qc_tests')
    op.drop_index(op.f('ix_qc_parameters_id'), table_name='qc_parameters')
    op.drop_table('qc_parameters')
    # ### end Alembic commands ###
